### ISSUE TITLE
weird format time bug in moment

### ISSUE THREAD

**Issue by artknight** [CounterMarch/moment.cfc#15]
```
<cfset date = new "/dailysandbox/cfc/lib/moment"("02/18/2016 12:10 PM")>
<cfdump var="#date.format("hh:mm tt")#" abort>
```

I get 12:02 PM and that is wrong.....

**Comment by atuttle** [comment]
your format string should be `hh:nn tt` not `hh:mm tt` ~ the "mm" is the month, which is why it's 02. :)

**Comment by artknight** [comment]
ah, damn it! you are correct!

**Comment by artknight** [comment]
Hi, just wondering.. I checked moment.js and they are using "mm" for minutes and "MM" for months. Do you think it would be possible to adjust this component to be fully compatible with the moment syntax?

**Comment by atuttle** [comment]
I don't see an overwhelming case for it. We're not aiming for complete parity with moment.js, and the current implementation is very much in line with dateTimeFormat() masks (in most cases, simply delegating to that method), which makes it familiar for existing CFML developers.

I'm not saying no, I'm saying convince me. ;)

**Comment by artknight** [comment]
Yeah, you are absolutely correct that the format does comply with the CF date/time format. Honestly I am not sure which way is better, but I do tend to put "mm" for months as a force of habbit and can imagine others, having worked with moment.js, will too. So, this would be a pure convenience change.
