### ISSUE TITLE
Wording from fromNow() returns

### ISSUE THREAD

**Issue by surgiie** [CounterMarch/moment.cfc#19]
Maybe its just me but the current return from the `fromNow()` method is somewhat confusing. If its less than 7 days will return `Last Someday`. This to me, can be a bit confusing say you had passed yesterdays date to the component it would return `Last Wednesday` which can be a bit confusing for some. Even though i think thats technically correct, some would think Last Wednesday as in 1 week ago Wednesday and not Yesterday. Would it be better to further check `diff` and return either `yesterday` or `# days ago`? And modify the weeks to return `Last Someday` or as it already is `# weeks ago`?

**Comment by atuttle** [comment]
I agree. What do you think about these rules?

- If diffDays < 2: `Yesterday`
- 7 > diffDays >= 2: `N days ago`
- Change "last week" to "1 week ago"

**Comment by surgiie** [comment]
Thats perfect! @atuttle

**Comment by atuttle** [comment]
Would you mind submitting a PR, @surgiie ?

**Comment by atuttle** [comment]
After a few seconds scanning your profile I'm guessing you may not have done a ton of PRs. No worries, I'm happy to help! In case you're interested, [here's some advice I put together for PR beginners](http://adamtuttle.codes/your-first-github-pull-request/).

**Comment by surgiie** [comment]
@atuttle I can do that! and yeah havent done many PRs in general, but im a little familiar with the process. Ill check out your guide first though! Thanks!
