### ISSUE TITLE
DST issue in UTCtoTZ() and TZtoUTC()

### ISSUE THREAD

**Issue by dswitzer** [CounterMarch/moment.cfc#5]
There's an issue when converting times from local to UTC and vice versa. The issue is when you get the offset, you get the offset based upon the current time stamp. 

For example, if you were to UTCtoTZ("2015-02-01 05:00:00", "America/New_York"), you should get midnight. However, if you run the code today, the offset is going to be -4, instead of -5. This is because you're getting the current timestamp for the offset.

To resolve the problem, you need to feed the offset in the date/time of what you're converting.

Here's a sample of the logic I've used in the past when converting local to UTC:

```
// get the milliseconds from epoch of the supplied date/time
var ms = timezone.getOffset( javacast("long", dateDiff("s", createDateTime(1970, 1, 1, 0, 0, 0), arguments.time)) )*1000;
```

This would get the seconds from Epoch of the time that you supplied, so you're getting the correct offset based on the time you supplied.

**Comment by atuttle** [comment]
I'm trying to figure out a test case. I guess I can use `isDST()` and the relative known that `America/New_York` will either be -4 or -5 to determine the expected value, and test the actual result against that, so that the tests aren't DST dependent.

**Comment by atuttle** [comment]
I have what I think is a good test. Validate it for me?

```
it("returns the offset in seconds (considering DST) of the specified zone", function(){
    var offset4h = -4*60*60;
    var offset5h = -5*60*60;

    // America/New_York is either -5 or -4 depending on DST (at time of writing :P)
    var m = moment( now(), 'America/New_York' );
    var expectedOffset = m.isDST() ? offset4h : offset5h;

    expect( m.getZoneOffset( 'America/New_York' ) ).toBe( expectedOffset );

    debug( expectedOffset, 'expected' );
    debug( m.getZoneOffset( 'America/New_York' ), 'actual' );

    debug( m.getDateTime(), 'before-convert' );
    debug( m.utc().getDateTime(), 'after-convert' );
});
```

Notice that I'm also debug-logging the before/after of a conversion to UTC. Based on that logging, I believe it's currently working as intended. I'm getting 3/23 17:25 local, 3/23 21:25 UTC, which matches http://www.worldtimeserver.com/current_time_in_UTC.aspx

Note that when I say "currently working as intended" I mean with my proposed fix -- NOT with the currently released version! :)

**Comment by atuttle** [comment]
Interestingly, if I revert back to using `getTickCount()`, the tests (including my proposed test above) all pass. I would seem, then, that (at least on my machine), CF is using the system time in MS as the value for `getTickCount()`. Granted, they document that ["The value of the counter has no meaning"](https://wikidocs.adobe.com/wiki/display/coldfusionen/gettickcount), so we _can't_ use it, because that probably means that for _some_ configuration out there, it _doesn't_ use return time in MS.

Anyway, I have an appropriate fix ready to go, if you can confirm that my test seems valid.

**Comment by atuttle** [comment]
Ah, after the 3rd or 4th reading of your report I think I finally get the crux of the issue. :)

I'm renaming `getZoneOffset()` to `getZoneCurrentOffset()` to more accurately reflect what it does, and I'll update the conversion functions to figure out the correct offset for conversion.

**Comment by dswitzer** [comment]
@atuttle 

I'd suggest never using now() in your unit tests for testing conversion--unless you explicitly testing getting the current time. Experience has taught me they tend to reveal bugs in unit tests. :)

To test what I believe the bug is, use a static date that falls when DLS was off (such as Feb 1, 2015). If I'm reading everything correctly, you're using the current timestamp to get the offset--not the offset as it was on Feb 1, 2015. So, instead of an offset of -5, if you run it for today, you're going to get -4 as the offset.

That's wrong.

Here's an example of what I'm talking about:

```
m = new moment("2015-02-01 00:00:00", "America/New_York");
writeDump(m.clone().utc().format("iso8061"));
```

The time should be 2015-02-01T05:00:00Z, not 2015-02-01T04:00:00Z. This is because on Feb 1, 2015 we were in EST, not EDT so the offset was -5, not -4. The places where you're getting the offset, you're always basing it on the offset right now--not what is when for the date supplied.

Make sense?

**Comment by atuttle** [comment]
It took me a while to figure that out, but yeah, I think I've got it now.

**Comment by dswitzer** [comment]
If it makes you feel any better, I made the same mistake initially. Thankfully I ended up having some unit tests in place that caught my mistake.

Something else I want to alert you to (although I don't think you'll get bit by the issue, at least not the way the code is now). In CF10 they made a change to native CF DateTime objects under the hood. It used to be that all Date objects were OleDateTime java objects. As of CF10, if you use dateConvert() to convert a date/time to UTC, it converts the object to a UTCOleDateTime. The problem is, if you do a math operation on a UTCOleDateTime object (like use createTimeSpan() to add to an existing date), you end up getting a OleDateTime back. The problem is, when CF converts the date from UTCOleDateTime to OleDateTime, the time is essentially converted back to local time--which ends up causing problems.

There's a number of bugs filed about this:

https://bugbase.adobe.com/index.cfm?event=bug&id=3777192
https://bugbase.adobe.com/index.cfm?event=bug&id=3338974
https://bugbase.adobe.com/index.cfm?event=bug&id=3309220
https://bugbase.adobe.com/index.cfm?event=bug&id=3347145

Since you're using Java under the hood, you shouldn't be bit by it. However, if you start working with dateConvert(), you could get bit by the bug.

**Comment by atuttle** [comment]
Thanks for the additional heads-up. Fortunately, you won't find any calls to `dateConvert()` in this project — by design. My server will be configured to run in UTC, so dateConvert is useless.

**Comment by dswitzer** [comment]
I strictly use UTC across all our servers now, but developers sometimes use local times, so our code still uses dateConvert() around now() instances to make sure we're dealing with UTC.

**Comment by atuttle** [comment]
So here's my updated test. Seem about right?

```
describe("utc()", function(){
    it("correctly calculates the utc value", function(){
        outsideDST = moment('2015-02-01 00:00:00', 'America/New_York').utc();
        insideDST = moment('2015-03-20 00:00:00', 'America/New_York').utc();

        expect( outsideDST.getZone() ).toBe( "UTC" );
        expect( outsideDST.format("HH:nn:ss") ).toBe( '05:00:00' );
        expect( insideDST.format("HH:nn:ss") ).toBe( '04:00:00' );
    });
});
```

**Comment by atuttle** [comment]
That last test helped me identify a bug in your originally suggested logic. :)

```
time = parseDateTime('2015-03-20 00:00:00');
zone = "America/New_York";

writeDump(var={time:time},label="start, in #zone#");

timezone = createObject('java', 'java.util.TimeZone').getTimezone( zone );
epoch = createDateTime(1970, 1, 1, 0, 0, 0);
seconds = timezone.getOffset( javacast('long', dateDiff('s', epoch, time)*1000) )/1000;
utcTime = dateAdd('s', -1*seconds, time);

writeDump(var={utcTime:utcTime, epoch:epoch, seconds:seconds},label="after, in UTC");
```

`timeZone.getOffset` returns MS, `dateDiff` is returning seconds, so your `*1000` was in the wrong place, and in my case (to add seconds) I also needed to divide it back out to convert back to seconds.

Regardless, this is awesome. Thank you so much!

**Comment by dswitzer** [comment]
@atuttle 

Funny enough, your seconds logic is what I'm actually using. I just mucked up the code trying to translate it to milliseconds!
